### ISSUE TITLE
Change size of "Start" Menu

### ISSUE THREAD

**Issue by NekkiNeks** [ramensoftware/windows-11-start-menu-styling-guide#75]
Is there any way I can resize the entire Start window? Which selector in the “Target” field should I use for this?

**Comment by m417z** [comment]
You can look at how existing themes do that, for example https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/RosePine/README.md.

**Comment by IanGaffaney** [comment]
I am absolutely certain this is not the most efficient way to do it, but it worked for me (you will have to fidget with the values for α):

```
- target: StartDocked.StartSizingFrame
    styles:
      - MinHeight=α
      - MaxHeight=α
```

If this clashes with the other segments of the menu, such as the "Pinned" label and "All Apps" button at the top, or the power and user profile buttons at the bottom, you'll need to edit other values such as:

```
- target: Windows.UI.Xaml.Controls.Grid#InnerContent
    styles:
      - Margin=0,-α,0,0
- target: Windows.UI.Xaml.Controls.Grid#MainContent
    styles:
      - Margin=1,1,1,-α
```
